-- Export script: ModEquivalencies
-- Reads ModEquivalencies.datc64 and writes src/Data/ModEquivalencies.lua
-- Run via the PoB export tool (same way as other Scripts/*.lua files)
--
-- ModEquivalencies maps each source mod ID to its upgraded equivalent.
-- Used by Way of the Stonefist (CalcPerform) to transform glove explicit mods.
--
-- Expected datc64 schema (PoE2):
--   ModsKey          : ref to Mods (the source mod being replaced)
--   EquivalentModsKey: ref to Mods (the upgraded replacement mod)

local out = io.open("../Data/ModEquivalencies.lua", "w")
out:write("-- This file is automatically generated, do not edit!\n")
out:write("-- Item data (c) Grinding Gear Games\n\n")
out:write("-- Maps source mod ID -> upgraded equivalent mod ID\n")
out:write("-- Used by Way of the Stonefist to transform glove explicit modifiers.\n")
out:write("return {\n")

local count = 0
for row in dat("ModEquivalencies"):Rows() do
	-- The source mod and its upgraded equivalent.
	-- Field names reflect the PoE2 datc64 schema; if extraction fails,
	-- check the schema in the export tool and update field names below.
	local srcMod = row.ModsKey
	local dstMod = row.EquivalentModsKey

	if srcMod and dstMod and srcMod.Id and dstMod.Id then
		out:write('\t["', srcMod.Id, '"] = "', dstMod.Id, '",\n')
		count = count + 1
	end
end

out:write("}\n")
out:close()

ConPrintf("ModEquivalencies: exported %d entries to ../Data/ModEquivalencies.lua", count)
if count == 0 then
	ConPrintf("WARNING: 0 entries written. Check field names ModsKey/EquivalentModsKey match the datc64 schema.")
	ConPrintf("Run: dat('ModEquivalencies'):Rows() and inspect row fields manually if needed.")
end
