-- This file is automatically generated, do not edit manually.
-- Item data (c) Grinding Gear Games

-- Maps raw glove explicit mod text to upgraded equivalent mod text.
-- Used by Way of the Stonefist (CalcPerform.lua) to transform glove explicit modifiers
-- when the GloveExplicitModTransform flag is active.
--
-- Keys: the exact text of an explicit mod line as it appears in src/Data/Uniques/gloves.lua
--   (i.e. the range-format text such as "(80-100)% increased Armour").
-- Values: the upgraded equivalent mod text (same format) that replaces it during calculation.
--
-- Only BASE and INC mod types are remapped; FLAG-type mods (e.g. "Culling Strike") are left
-- active unchanged because they cannot be meaningfully negated.
--
-- To regenerate from game data: run src/Export/Scripts/modequivalencies.lua via the PoB
-- export tool, then update this file with the resulting entries.
return {
}
